### ISSUE TITLE
[建议] 软件窗口不支持最大化，显示不完全

### ISSUE THREAD

**Issue by ItosEO** [Uotan-Dev/UotanToolboxNT#27]
**描述**
软件窗口不支持最大化，显示不完全

**截屏**
![image](https://github.com/user-attachments/assets/dc8063a4-ecd1-416b-8350-4828b4bda3eb)

**建议**
加入窗口最大化和自定义大小

**Comment by yuzh0816** [comment]
此问题优先级较低，暂时不予处理，建议先自行调整缩放比例解决。

**Comment by 13584452567** [comment]
问题暂时挂起，等待上游代码稳定后更新低分辨率布局。
工具箱目标分辨率为1240x840。1080p下100缩放可完整显示，125缩放需要开启自动隐藏任务栏才能显示完全，150缩放显示缺失下半1/5。标准2k分辨率下只要缩放不高于175均可显示完全。

**Comment by 13584452567** [comment]
3.1版本已处理完毕
