### ISSUE TITLE
建议编译发布新增Appimage格式的应用包

### ISSUE THREAD

**Issue by 8MiYile** [Uotan-Dev/UotanToolboxNT#29]

**Comment by 13584452567** [comment]
考虑过这件事，但是appimage貌似不会自己生成桌面环境快捷方式

**Comment by 8MiYile** [comment]
@13584452567 哥们啊 appimage文件能丢在桌面打开的
啊你要是说桌面快捷方式这种的 可以让他们用AppimageLauncher管理

**Comment by mujianwu** [comment]
主要是在部分桌面环境下不会正常显示程序图标，我们也试了QQ官方提供的appimage文件，同样不显示图标，在ARM等其他架构上还有其他问题，所以暂时放弃了这种打包方式。

**Comment by 8MiYile** [comment]
@mujianwu 因为我这里只测试了DDE环境的
![截图_选择区域_20240731194536](https://github.com/user-attachments/assets/2b1239b8-336b-479f-ba44-53646ade3dee)
这些带版本号显示的全是 AppImageLauncher 显示的

**Comment by mujianwu** [comment]
嗯，部分环境是没问题，但是使用人数较多的GNOME是没有图标的。
