### ISSUE TITLE
安装路径不可选吗

### ISSUE THREAD

**Issue by yiteei** [Uotan-Dev/UotanToolboxNT#30]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by 13584452567** [comment]
目前安装器并未做此功能。可考虑使用免安装版自行解压至目标路径

**Comment by yuzh0816** [comment]
下一版本安装器可能会添加此选项。

**Comment by mujianwu** [comment]
3.2版本已增加此功能
