### ISSUE TITLE
[BUG] 请更新  Scrcpy 以支持 Android 14设备

### ISSUE THREAD

**Issue by Lparksi** [Uotan-Dev/UotanToolboxNT#31]
**Describe the bug**
请更新  Scrcpy 以支持 Android 14设备
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by 13584452567** [comment]
运行bin目录内的scrcpy以获取日志。
没有日志的话，我只能算一卦了

**Comment by mujianwu** [comment]
下个版本会更新的

**Comment by Lparksi** [comment]
手动替换到新版本就解决了，不需要日志，说的很清楚了。
