### ISSUE TITLE
[Feature] 添加多语言自定义功能

### ISSUE THREAD

**Issue by hanyi0914** [Uotan-Dev/UotanToolboxNT#32]
在苹果的macOS操作系统时使用柚坛工具箱，我发现无法将柚坛工具箱语言设置为中文，这对我来说造成了很大的困扰。作为一个对相关领域知识不多且仅懂英文的用户，这个问题对我来说是一个严重的障碍。这个缺陷不仅让我的操作体验变得极其不便，而且使得我在使用系统时遇到了许多困难。希望能够尽快解决这个语言设置问题，以提升使用的舒适度和效率。
I have encountered a significant issue with macOS as it does not allow me to set the system language to Chinese. This is highly problematic for me, as I have limited knowledge in this area and only understand English. This defect not only makes my user experience extremely inconvenient but causes many difficulties while using the system. I hope this language setting issue can be resolved quickly to enhance usability and efficiency.
![CleanShot 2024-08-08 at 11 58 07@2x](https://github.com/user-attachments/assets/5942049b-3f96-4c76-98d7-632ac55bd515)

**Comment by yuzh0816** [comment]
下个版本添加多语言自定义功能

**Comment by hanyi0914** [comment]
> 下个版本添加多语言自定义功能

不说下苹果电脑英文是因为地区导致的

**Comment by yuzh0816** [comment]
> > 下个版本添加多语言自定义功能
> 
> 不说下苹果电脑英文是因为地区导致的

会在readme中添加的🤦‍♂️

**Comment by yuzh0816** [comment]
功能已添加
