### ISSUE TITLE
不应该指定为某一个terminal 而是应该打开用户的默认terminal

### ISSUE THREAD

**Issue by xzl01** [Uotan-Dev/UotanToolboxNT#35]
https://github.com/Uotan-Dev/UotanToolboxNT/blob/580109186cdf5440a1f4e32fb468e18253cc902b/UotanToolbox/MainView.axaml.cs#L41
https://github.com/Uotan-Dev/UotanToolboxNT/pull/36

**Comment by mengtianya-kou** [comment]
![image](https://github.com/user-attachments/assets/eb718e40-3eec-4620-99fb-2562a21e395c)
deepin v23 不能使用

**Comment by xzl01** [comment]
> ![image](https://private-user-images.githubusercontent.com/175811481/363131020-eb718e40-3eec-4620-99fb-2562a21e395c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMTI1NDUsIm5iZiI6MTcyNTAxMjI0NSwicGF0aCI6Ii8xNzU4MTE0ODEvMzYzMTMxMDIwLWViNzE4ZTQwLTNlZWMtNDYyMC05OWZiLTI1NjJhMjFlMzk1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQxMDA0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzZmMWU5MTA0Nzk5MzBlOWY5ZDRjNGNhMmIwOGMzODBkYTkxODQ5NWFhOWU3NWM5NjJkYzgwZDMwZmJlZDA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zqMQt1aWW1dARjrVkSlCgM8P6o8C27JznGy0bH9gosw) deepin v23 不能使用

因为这个是写死了依赖，它只需要终端实现相关功能，等pr合入之后修改打包依赖即可

**Comment by shenmo7192** [comment]
> > ![image](https://private-user-images.githubusercontent.com/175811481/363131020-eb718e40-3eec-4620-99fb-2562a21e395c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMTI1NDUsIm5iZiI6MTcyNTAxMjI0NSwicGF0aCI6Ii8xNzU4MTE0ODEvMzYzMTMxMDIwLWViNzE4ZTQwLTNlZWMtNDYyMC05OWZiLTI1NjJhMjFlMzk1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQxMDA0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzZmMWU5MTA0Nzk5MzBlOWY5ZDRjNGNhMmIwOGMzODBkYTkxODQ5NWFhOWU3NWM5NjJkYzgwZDMwZmJlZDA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zqMQt1aWW1dARjrVkSlCgM8P6o8C27JznGy0bH9gosw) deepin v23 不能使用
> 
> 因为这个是写死了依赖，它只需要终端实现相关功能，等pr合入之后修改打包依赖即可
x-terminal-emulator   

用这个？

**Comment by yuzh0816** [comment]
收到pr，等待我们评估下哈
