### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yuanxiwang** [Uotan-Dev/UotanToolboxNT#37]
UotanToolbox_MacOs_ARM64_3.0.0  
不能使用  
提示
”UotanToolbox“ 已损坏，无法打开

Apple M3 Pro
macOS 14.6.1(23G93)

**Comment by mujianwu** [comment]
注：
2、macOS运行须在终端执行命令：sudo xattr -r -d com.apple.quarantine UotanToolbox.app
