### ISSUE TITLE
[增强]应用管理搜索及显示应用名功能

### ISSUE THREAD

**Issue by fyhbauyg** [Uotan-Dev/UotanToolboxNT#40]
建议修改应用管理读取列表后添加搜索按钮，以及修改名称显示为[应用名]包名。

**Comment by fyhbauyg** [comment]
> 建议修改应用管理读取列表后添加搜索按钮，以及修改名称显示为[应用名]包名。

也许windwos版本已经有这些功能，但请在linux版本中添加。

**Comment by 13584452567** [comment]
计划通过类似scrcpy的方式实现
处理完成，将在3.2版本加入
