### ISSUE TITLE
[增强]支持 adb 连接电视机功能

### ISSUE THREAD

**Issue by SONGjiemo** [Uotan-Dev/UotanToolboxNT#41]
最近玩电视机，希望可以 adb 的 5555 端口连接电视机。做到安装软件，刷入固件这些功能

**Comment by mujianwu** [comment]
最新版的无线adb连接不行吗？

**Comment by SONGjiemo** [comment]
> 最新版的无线adb连接不行吗？

不是，我没有看到 adb 连接功能。
![image](https://github.com/user-attachments/assets/86286133-606d-4d30-ac11-cc346f0f1136)
请问一下，wo我是不是 弄错软件了还是什么情况

**Comment by mujianwu** [comment]
这不是最新版本，请检查更新，或去Releases里下载3.1.0版本
