### ISSUE TITLE
Linux端是否默认root权限启动比较好？

### ISSUE THREAD

**Issue by NeroBlackstone** [Uotan-Dev/UotanToolboxNT#46]
txt线刷弹出一个su权限申请，点击确定但是整个刷机过程卡住，导致最后刷机失败。
之后就没这个问题了。
所以柚坛是不是设置成默认su用户启动比较好？
如果其他人也有这个情况希望改成默认su用户，免得Linux新手用户不记得su启动导致刷机失败

环境：Linux 6.10 LTS arch linux，柚坛3.2.1

**Comment by mujianwu** [comment]
什么处理器呀

**Comment by NeroBlackstone** [comment]
> 什么处理器呀

intel i5 6200U

**Comment by 13584452567** [comment]
系统没有安装过Android-debug-bridge之类的软件包吗？

**Comment by NeroBlackstone** [comment]
装了android tools
``` shell
~> paru android-tools                                                                       1 2024年11月05日 21时42分21秒 下午
1 extra/android-tools 35.0.2-6 [0 B 6.27 MiB] [Installed]
    Android platform tools
```

**Comment by 13584452567** [comment]
一开始那个su请求应该是调整udev的，后面添加了就好了。

**Comment by 13584452567** [comment]
我反复思考了之后认为，工具箱不应该以su权限启动。su启动的话不仅存在风险问题，更有主程序行为异常的可能。
关于fastboot首次启动需要su的问题为打包时疑似脚本处理缺陷，在后续尝试修复。
