### ISSUE TITLE
[BUG] 启动失败

### ISSUE THREAD

**Issue by xiang473535976** [Uotan-Dev/UotanToolboxNT#47]
![1730774453360](https://github.com/user-attachments/assets/38e766a3-6b77-4066-9d66-1d94f49c2188)
小米13   fastboot模式 刷入，选择临时启动，， 弹窗提示 启动失败

**Comment by mujianwu** [comment]
1.手机重进fastboot再次尝试
2.确保该镜像文件是可被直接启动的

**Comment by xiang473535976** [comment]
> 1.手机重进fastboot再次尝试 2.确保该镜像文件是可被直接启动的
试了  不行  换了小米11   小米12  小米13的   recovery  都不行

**Comment by mujianwu** [comment]
那点击左下角的终端。输入 fastboot boot ”您的镜像文件路径“ 回车看看什么情况
