### ISSUE TITLE
[增强]自动保存/关闭警告

### ISSUE THREAD

**Issue by fyhbauyg** [Uotan-Dev/UotanToolboxNT#48]
为scrcpy添加ini配置文件之类的，默认显示点按操作的选项让我每次都要去开发者选项关掉。
在修改分区中的警告可以为右上角设置添加关闭警告的按钮以及在弹出的警告中添加不再提示的按钮。
可能是没适配kernelsu或是修改分区的功能没做好，我无法读取分区。（安卓12）
如果不是没做好这个功能的原因可以回复我并且协助我适配。
修改应用管理的选择为多选并且添加全选，这让我可以快速备份应用。

总结
1.添加配置文件
2.为警告添加不在提示按钮
3.适配机型/kernelsu
4.为应用管理修改多选和添加全选按钮。
#感谢开发者制作的这个工具箱和采纳了为应用管理添加搜索的建议。
这个题案只是作为参考优化项目，开发者自行选择。

**Comment by mujianwu** [comment]
第一个问题与您的手机厂商的设置有关，工具箱未设置相关内容。修改分区部分由于风险较大目前计划确实想让他每次使用时弹出警告。读取分区表再ksu设备上确实由于未知问题，不会弹出权限请求，在ksu管理器中手动对shell授予权限即可正常读取。应用管理的多选设置还有待商讨（本人挺想加入的，但负责该页面的开发似乎并不想）。

**Comment by 13584452567** [comment]
1.尝试关闭工具箱的显示触摸位置配置。若该设置无效，则为厂商修改了投屏设置。目前的设置持久化设置为仅针对几个选项的特殊适配，等待通用化该框架后对所有设置进行持久化保存。
2.不在预期之内。修改分区为极度危险操作，需要再三思考。
3. 关联[issue](https://github.com/tiann/KernelSU/issues/2045)，尝试回退KSU版本至0.9.3之前进行复现。此问题疑似为KSU上游问题
4. 应用多选涉及UI改动，需等待我们的前端有空回来修改相关逻辑。

**Comment by fyhbauyg** [comment]
> 第一个问题与您的手机厂商的设置有关，工具箱未设置相关内容。修改分区部分由于风险较大目前计划确实想让他每次使用时弹出警告。读取分区表再ksu设备上确实由于未知问题，不会弹出权限请求，在ksu管理器中手动对shell授予权限即可正常读取。应用管理的多选设置还有待商讨（本人挺想加入的，但负责该页面的开发似乎并不想）。

ksu的授权是白名单只有手动授权root的，我在命令行输入adb shell然后su可以正常使用root权限。

**Comment by fyhbauyg** [comment]
> 1.尝试关闭工具箱的显示触摸位置配置。若该设置无效，则为厂商修改了投屏设置。目前的设置持久化设置为仅针对几个选项的特殊适配，等待通用化该框架后对所有设置进行持久化保存。 2.不在预期之内。修改分区为极度危险操作，需要再三思考。 3. 关联[issue](https://github.com/tiann/KernelSU/issues/2045)，尝试回退KSU版本至0.9.3之前进行复现。此问题疑似为KSU上游问题 4. 应用多选涉及UI改动，需等待我们的前端有空回来修改相关逻辑。

在你关联的issue中我看到这个[回复](https://github.com/tiann/KernelSU/issues/2045#issuecomment-2337081454)我尝试了很多终端都是正常使用su命令的，至于"尝试回退KSU版本至0.9.3之前进行复现"，由于我的内核是非gki的所以不好回退，等有时间我找个同机型的试验magisk可不可以使用修改分区确认是否是厂家问题。
oppoa92s
mtk6873(天玑800)

**Comment by fyhbauyg** [comment]
> 1.尝试关闭工具箱的显示触摸位置配置。若该设置无效，则为厂商修改了投屏设置。目前的设置持久化设置为仅针对几个选项的特殊适配，等待通用化该框架后对所有设置进行持久化保存。 2.不在预期之内。修改分区为极度危险操作，需要再三思考。 3. 关联[issue](https://github.com/tiann/KernelSU/issues/2045)，尝试回退KSU版本至0.9.3之前进行复现。此问题疑似为KSU上游问题 4. 应用多选涉及UI改动，需等待我们的前端有空回来修改相关逻辑。

已经测试magisk，七个选项都尝试过了，都显示无法获取分区，每当点击获取分区就会弹出shell已授权root的magisk提示。
所以这是工具或者厂商的问题

**Comment by mujianwu** [comment]
手机上的Shell每次都会请求权限？

**Comment by mujianwu** [comment]
你尝试一下工具箱的3.1版本能否正常读取

**Comment by fyhbauyg** [comment]
> 手机上的Shell每次都会请求权限？

不是这个意思，magisk当应用调用root权限时就会提示。

**Comment by fyhbauyg** [comment]
> 你尝试一下工具箱的3.1版本能否正常读取

我已经换了apatch，工具箱突然可以读取了就在sdc的选项

**Comment by mujianwu** [comment]
之前sdc也不行吗？

**Comment by fyhbauyg** [comment]
> 之前sdc也不行吗？

对

**Comment by fyhbauyg** [comment]
![屏幕截图(3)](https://github.com/user-attachments/assets/8da52b88-bb44-4e4b-ab49-50b4fc946cd2)
修改分区可以了提取分区还是不行，如果有时间可以在星期六给我远程测试一下。
q:1305025803

**Comment by mujianwu** [comment]
你的运行目录有空格吧

**Comment by 13584452567** [comment]
有事Q群里说：975952599
