### ISSUE TITLE
[增强]建议集成payload dumper的解包功能

### ISSUE THREAD

**Issue by whx9986** [Uotan-Dev/UotanToolboxNT#49]
这款工具箱真的是目前最好用的刷机应用了，ui好看，还有很多丰富的功能，唯一有点可惜的是没有解包功能，如果可以加上5ec1cff大佬开发的payload.bin多线程解包工具[payload dumper](https://github.com/5ec1cff/payload-dumper?tab=readme-ov-file)，简直就是完美了，当然这只是一个建议。

**Comment by 13584452567** [comment]
计划加入固件解包支持，但是由于人手不足，期限不定。

下个版本估计是赶不上了，预计是下下个版本的规划内容

我已经基于那个的源码使用C#重新构建了一个命令行程序，有兴趣的话可以先用那个。

https://wweo.lanzouj.com/iMfq52fje90f
密码:5b3r
