### ISSUE TITLE
[BUG] 关闭应用后不会结束adb和hdc子进程

### ISSUE THREAD

**Issue by allyxmiko** [Uotan-Dev/UotanToolboxNT#51]
**Describe the bug**
关闭应用后不会结束adb和hdc子进程

**To Reproduce**
1. 打开应用
2. 使用完毕后关闭应用

**Expected behavior**
随着应用关闭会自动结束adb和hdc进程。

**Screenshots**
![PixPin_2024-11-17_22-25-00](https://github.com/user-attachments/assets/330f8fbb-9e6e-4f76-9605-74c488f48e2a)

**Additional context**
软件版本：3.2.1（x64免安装）

**Comment by mujianwu** [comment]
@13584452567
