### ISSUE TITLE
[增强]刷入前自动检测设备状态并重启至目标模式

### ISSUE THREAD

**Issue by Tobapuww** [Uotan-Dev/UotanToolboxNT#57]
## **问题描述**
目前，工具箱在执行刷入相关操作时需要用户手动将设备切换到特定模式（如 Recovery 模式或 Fastboot 模式）。尽管工具箱主页的“重启至”功能已经支持自动检测设备状态并切换模式，但其他刷入相关功能（如“预置分区刷入”、“自定义分区刷入”、“同步 A/B 分区”等）尚未实现这一功能，用户体验上存在些许不便。

---

## **建议内容**
为提升用户体验，建议在以下刷入功能中，自动检测设备当前启动状态并根据需要切换至目标模式：  
1. **预置分区刷入**  
2. **自定义分区刷入**  
3. **同步 A/B 分区**  

具体优化方向：  
- **设备状态检测：** 在执行刷入操作前，自动检测设备的当前启动状态。  
- **自动重启：** 如果设备未处于目标模式（如 Recovery 或 Fastboot），工具箱应自动将设备重启至对应模式**并提醒用户确认**，无需用户手动切换。  
- **提示信息：** 在切换模式前提供明确的提示，确保用户知晓正在进行的操作。

---

## **预期行为**
- 在用户发起刷入操作时，工具箱能够自动检测设备启动状态，并根据需要重启至目标模式（如 Recovery 或 Fastboot 模式）。  
- 用户无需手动操作即可进入刷入所需模式，提升操作便捷性。

---

## **实际行为**
- 目前，刷入操作需要用户自行将设备切换至目标模式，部分用户可能因为不了解流程而导致刷入失败。
- 
![a838d412564786315aa7b79d7250320f](https://github.com/user-attachments/assets/a32cce4b-5451-4b7a-b9d9-1aea229a92b1)

---

## **建议意义**
- **提高易用性：** 减少用户手动操作，提高工具箱的智能化水平。  
- **避免错误操作：** 自动检测和切换模式可以降低用户因设备状态不正确而导致刷入失败的概率。  
- **增强一致性：** 与主页“重启至”功能的自动检测逻辑保持一致性。

---

## **附加信息**
如需更多建议或测试反馈，请联系，我愿意协助进一步完善功能。

---

## **结语**
感谢开发团队的辛勤付出！希望该建议能够进一步提升工具箱的用户体验，也愿意协助进行相关功能的测试和反馈。

**Comment by mujianwu** [comment]
考虑到误点以及小白可能在不知道其具体作用的情况下进行操作暂不考虑增加此自动进入模式功能。
